### ISSUE TITLE
Vulpera racial

### ISSUE THREAD

**Issue by Ciante79** [artscout/Broker_portals#14]
I tried adding myself but broke everything :D

Can you please add the Vulpera racial?

312370 -- Make Camp
312372 -- Return to Camp

**Comment by artscout** [comment]
Yeah, after I finish with planned features I;m working on

**Comment by artscout** [comment]
Please check if that works

**Comment by Ciante79** [comment]
Yes! Works great!
thanks

**Comment by artscout** [comment]
ok then )
