### ISSUE TITLE
Few missing hearthstone toys to add

### ISSUE THREAD

**Issue by Ciante79** [artscout/Broker_portals#4]
Hi,

there is a few missing hearthstone toy that you might want to add:

183716 -- Venthyr Sinstone
190196 -- Enlightened Hearthstone
190237 -- Broker Translocation Matrix
206195 -- Path of the Naaru

Also, Ruby Slippers appears twice:

![Screenshot 2024-04-12 195854](https://github.com/artscout/Broker_portals/assets/120906376/5ca273f8-227d-4c76-b55e-79dfb5105044)

**Comment by artscout** [comment]
Fixed that, thanks!
