### ISSUE TITLE
Needs scrollbar

### ISSUE THREAD

**Issue by MysticalOS** [artscout/Broker_portals#6]
If you're on a char like mine who's done every M+ or challenge mode to date, plus tons of toys and is engineer, lets just say portals menu is VERY long. to point i can't even access entire thing.

it needs a scrollbar, or possibly just refactoring into sub categories, maybe wormholes, dungeon teleports etc in sub menus?

![Screenshot 2024-08-21 at 8 01 54 PM](https://github.com/user-attachments/assets/c978de47-9ac8-431d-badd-33212881d580)

**Comment by artscout** [comment]
Still WIP. But nearly done )

**Comment by artscout** [comment]
Though it works :) report if something wrong
