### ISSUE TITLE
G.E.A.R. Tracking Beacon appears as Hearthstone

### ISSUE THREAD

**Issue by Ciante79** [artscout/Broker_portals#9]
The G.E.A.R. Tracking Beacon (the alternative to flight master's whistle for Gnome character who have done thier heritage quest) is appearing in 2 places, both in the generic items list and in the heartstone alternative list, removing line 141 should fix it

line 118 (correct):
    168862 -- G.E.A.R. Tracking Beacon

line 141 (wrong):
    168862, -- G.E.A.R. Tracking Beacon

**Comment by artscout** [comment]
Fixed

**Comment by Ciante79** [comment]
I think you removed the wrong line

The item is an alternative version of the flight master's whistle, but now is only visible in the hearthstone menu (it's not an hearthstone)

**Comment by artscout** [comment]
oh ) I will fix it with the next release but it will be ready maybe tomorrow, not sure.
